apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: next-tls
spec:
  secretName: next-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: gsd-payments.com
  dnsNames:
  - gsd-payments.com
